### ISSUE TITLE
Duel Requests is not translateable

### ISSUE THREAD

**Issue by UnioDex** [Realizedd/Duels#11]
http://prntscr.com/m5t6su

Version: 3.2.3

In /duel stats requests are not translateable. It says enabled or disabled but i need to change them.

**Comment by Realizedd** [comment]
Support for those will be added in the next update.

**Comment by Realizedd** [comment]
Added section [`GENERAL`](https://github.com/Realizedd/Duels/blob/master/duels-plugin/src/main/resources/lang.yml#L13) in 0041f82 which allows translating those messages. Thanks for the suggestion.
