### ISSUE TITLE
Inventory Bug when change of gamemode

### ISSUE THREAD

**Issue by austin9240** [Realizedd/Duels#15]
**Replicate**
This bug occurs when using a plugin such as per world inventory and the player is joining a duel when they are in a different game mode. For example, on my server, there is a creative world and if they join a duel from that world their inventory will not update with the proper kit and will instead give the survival inventory that they had before joining the creative world. Then when the duel is over they will lose their entire survival inventory as the inventory is normally cleared at the end of a duel. I think the reason for this occurring is because the kit is actually given a fraction of a second before they are teleported into the arena.

**Proposed Solutions** 
Make it so the player is first teleported and then the kit is given or make it so certain world can be disabled for joining a duel

**Comment by Realizedd** [comment]
Added [`blacklisted-worlds`](https://github.com/Realizedd/Duels/blob/master/duels-plugin/src/main/resources/config.yml#L212) in 0041f82, thanks for reporting.
