### ISSUE TITLE
Tridents with Loyalty enchant not work on Duels

### ISSUE THREAD

**Issue by andris155** [Realizedd/Duels#26]
Trident with Loyalty enchant not came back to player.
![64196113-67431d00-ce83-11e9-8ccb-b23f99156dcf](https://user-images.githubusercontent.com/8324198/64276228-b81c4980-cf47-11e9-87cf-ead05c08c52e.png)

**Comment by Realizedd** [comment]
Fixed in bb57ba7.

**Comment by andris155** [comment]
Thanks
