### ISSUE TITLE
Failed to start the match: Arena is already in use

### ISSUE THREAD

**Issue by DogeTennant** [Realizedd/Duels#31]
I can't start any duel, because it always says that the arena that I select (or even when I leave it random) is in use, doesn't matter if I create 10 arenas and choose one of them or let it go random, or if I create just one arena, it just always says that the arena is already in use.. Any solutions?

Thanks in advance!

Also I'm running on 1.15.2

**Comment by Realizedd** [comment]
Looks like arenaspecific is on for the kit. Disable it using `/ds options`.
