### ISSUE TITLE
bug /duel toggle 3.4.0

### ISSUE THREAD

**Issue by Naoya99** [Realizedd/Duels#32]
Hello,
I have version 3.4.0 and the /duel toggle does not work. We always receive duel requests.
![image](https://user-images.githubusercontent.com/45720987/80531287-a9811780-899a-11ea-98ee-1965f3126c86.png)
"You are no longer accepting duel requests."
![image](https://user-images.githubusercontent.com/45720987/80531392-daf9e300-899a-11ea-954e-07e0e30c3d5d.png)

duels: 3.4.0
Paper: build 213
worldguard: 7.0.3 SNAPSHOT;2030-17c1647

**Comment by Realizedd** [comment]
If you have the permission `duels.admin`, you'll be able to send the request no matter if they have it disabled or not.

**Comment by Naoya99** [comment]
ok, great I thought it was a bug. thank you
