### ISSUE TITLE
Issue with shift-clicking to open container while dueling

### ISSUE THREAD

**Issue by AerWyn81** [Realizedd/Duels#33]
Hello, I use CMI which allows, among other things, to open a shulkerbox by shift-clicking. When a player is in combat and tries to open the shulkerbox, it refuses, fine. When the duel is over, the player can no longer re-open his shulkerbox and must disconnect to re-open it. When the player re-opens the shulkerbox, **all the contents has disappeared.** Is there any way to fix this? Should I check with you or CMI?

**Comment by Realizedd** [comment]
It seems like an issue with CMI. The dev will probably need to check if the box has successfully opened by listening for interactions with the inventory or cancellation of InventoryOpenEvent.

**Comment by AerWyn81** [comment]
Hi, CMI does not manage the inventories as they answered me on their git, it only opens the shulkerbox. I configured a server with only CMI/Duels plugins. As enabled on our server : 

duel:
  use-own-inventory:
    # If set to 'true', player's own inventory will be used in a duel instead of kits.
    # NOTE: If this option is enabled, Kit Selector will be inaccessible in the Setting GUI.
    # default: false
    enabled: true

    # If set to 'true', players will keep their inventory items on death.
    # default: false
    keep-items: true

I think it's an issue when the plugin tries to restore the inventory, it doesn't seem to restore the shulkerbox inventory.

**Comment by Realizedd** [comment]
With use-own-inventory set to true, there isn't really a restoration process by Duels, so that can't be the issue. Could you check if players are able to open the box with contents by placing it on the ground after the duel? It would be a simple way to check my assumption.

**Comment by AerWyn81** [comment]
I just tried it. Indeed, after the duel if I place the shulker on the ground, there are the contents. On the other hand, if I disconnect after the duel and reconnect, the contents are empty.
