### ISSUE TITLE
Placeholder Wins/Losses dosn't work

### ISSUE THREAD

**Issue by Atlantiis31** [Realizedd/Duels#41]
Hi,

I have a bug with **wins** and **losses** placeholders. 
They don't work in scoreboard plugin like "RealScoreboard".

**The [Duels Extension] Placeholders 1.0.3 work perfectly.**

The problem concern only the placeholders:
- %duels_wins%
- %duels_losses%

I use latest version of plugin and PlaceHolderAPI 2.10.6

Thansk for your help ! :)

**Comment by Realizedd** [comment]
Should be fixed in 59a875c.
