### ISSUE TITLE
Removing Armor while full inventory deletes the armor!

### ISSUE THREAD

**Issue by Draesia** [Realizedd/Duels#51]
I received this report from my players:

In the duel arena I was trying to take off my armor for a fistfight, and my inventory was full. I accidentally pressed q, which would have dropped the armor straight from the armor slot, but you can't drop items in the duel arena. Usually when you drop an item in the duel arena, it will put it back in your inventory, but since my inventory was full, it just disappeared. 

I have just tested this myself and I can confirm that the issue is legit and is bugged.

**Comment by Realizedd** [comment]
Fixed in 59a875c.
