### ISSUE TITLE
[BUG] Lose inventory

### ISSUE THREAD

**Issue by emanondev** [Realizedd/Duels#55]
Duels may lose your inventory after a duel

Steps to reproduce:
- start a duel
- get killed and don't click "respawn"
- get kicked on quit the server
- wait server restart
- relog

Solutions:
- A: force player respawn after getting killed in a duel
- B: save inventory on file to load it back after restart

config:
https://pastebin.com/uY3AQhEe

**Comment by iBuseWinner** [comment]
Same but without server restarting :/
@Realizedd plz fix this bug

**Comment by Realizedd** [comment]
Fixed in 59a875c.
