### ISSUE TITLE
Issue with new version of Essentials

### ISSUE THREAD

**Issue by nivcoo** [Realizedd/Duels#58]
Hello, can you update the hook with the new verison of essentialsX ?

**Comment by awgybop1** [comment]
To elaborate:

The latest version of EssentialsX (2.19.0) contains breaking API changes which prevents Duels from setting the player's /back location successfully. This prevents Duel matches from starting if the option is enabled in the config.

To users experiencing this issue, you can:
A.) Disable the option in the config to patch the Essentials /back command.
OR
B.) Don't update to EssentialsX 2.19.0

**Comment by Realizedd** [comment]
Fixed in 59a875c.
