### ISSUE TITLE
Binding kit does not work

### ISSUE THREAD

**Issue by AkariDream** [Realizedd/Duels#60]
*heres how it can be triggered
1.select a map
2.select kit
3.confirm and send duel
4.you get a kit battle that is not suitable for use on this map

when the player selects kit first then selects the map
that way, it will be restricted by binding kits
I hope you can fix it as soon as possible
because my players usually choose the wrong kit when it comes to duels

**Comment by Realizedd** [comment]
Do you have arenaspecific enabled for the kit?

**Comment by Realizedd** [comment]
Fixed in 3e4c0ca
